# Generated by Django 4.0.1 on 2022-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cart', models.IntegerField()),
                ('order_history', models.IntegerField()),
            ],
        ),
    ]
