# Generated by Django 4.0.1 on 2022-01-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_id_user_user_id_remove_user_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prices',
            new_name='price',
        ),
    ]
