# Generated by Django 4.0.1 on 2022-01-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_prices_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='fk_author',
            new_name='author_fk',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fk_user_id',
            new_name='user_fk_id',
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.item')),
                ('order_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.cart')),
                ('item_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user'),
        ),
    ]
