# Generated by Django 4.0.1 on 2022-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_rename_fk_author_item_author_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
