# Generated by Django 4.0.1 on 2022-02-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_fk_user_id_alter_cartitem_cart_fk_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fk_user_id',
            new_name='user_fk_id',
        ),
    ]
