# Generated by Django 4.0.1 on 2022-02-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_fk_user_id_cart_user_fk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
